service: linkmow-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  stage: prod
  timeout: 10
  region: us-east-1

functions:
  serverAPI:
    handler: handler.serverAPI
    environment:
      ACCESS_KEY_ID : 
      SECRET_ACCESS_KEY : 
      DEFAULT_REGION : 
    events:
      - httpApi:
          path: /{proxy+}
          method: any

configValidationMode: error
